export const CopanPlatformQuest = () => {
  return (
    <>
      Copan Platform: Design System for the Loft Group.<br /><br />
      The challenge was to provide a platform in which several Design Systems could be generated by reusing code, while respecting different brands and technology requirements from companies within the group and having flexibility on components implementations.<br /><br />
      Creation of an architecture built as a platform aimed for contribution. Implementation of Base Design Tokens and Base Components that were extended for each brand Design System lib, applying specific styles for the desired brand and extra functionalities when needed.<br /><br />
      6 libs were delivered in less than 6 months, 4 in React and 2 in Flutter, with custom brands for different companies within the group.<br /><br />
      <span>[ Stack: Style Dictionary / React / Stitches / Flutter ]</span>
    </>
  );
};
    